import Head from 'next/head'
// import ImageHover1 from '../component/ImageHover';
import React, { useEffect, useRef,useState } from 'react';
import next from 'next';
import About from '../component/aboutPage'
import Capabilities from '../component/Capabilities'
// import React, { useEffect, useRef,useState } from 'react';
// import  gsap  from 'gsap';
import Testimonial from '../component/testimonial'
import Awards from '@/component/awards';

export default function about() {
    return (
        <>
          <Head>
            <title>clay global</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="images/icons/favicon.png" />
          </Head>
          
           <About></About>
           <Capabilities></Capabilities>
           <Awards></Awards>
           <Testimonial></Testimonial>
            {/* <CalltoActionthree></CalltoActionthree> */}
          </>
  )
}
