import Head from 'next/head'
import ImageHover1 from '../component/ImageHover';
import React, { useEffect, useRef,useState } from 'react';
import next from 'next';
import Testimonial from '../component/testimonial';
// import React, { useEffect, useRef,useState } from 'react';
// import  gsap  from 'gsap';

export default function clients() {
    return (
        <>
          <Head>
            <title>clay global</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="images/icons/favicon.png" />
           
          </Head>
    
            <ImageHover1></ImageHover1>
            <Testimonial></Testimonial>
           
            {/* <CalltoActionthree></CalltoActionthree> */}
          </>
  )
}
