import Head from 'next/head'
import React from 'react';
import next from 'next';
import ImageHover1 from '../component/ImageHover';
import ContactContent from '../component/contactContent';

export default function clients() {
    return (
        <>
            <Head>
              <title>clay global</title>
              <meta name="description" content="Generated by create next app" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
              <link rel="icon" href="images/icons/favicon.png" />
            </Head>
            <ContactContent></ContactContent>
          </>
  )
}
